import raw from './contributions.json'

/**
 * Merged pull requests into repositories Jay does not own.
 *
 * Generated by scripts/fetch-contributions.mjs, checked in rather than
 * fetched at build time: the site should build with no network, and a number
 * on a page about someone's work should not change because GitHub was slow.
 * Re-run the script to refresh it.
 */
export interface Contribution {
  repo: string
  count: number
  first: string
  last: string
}

export interface Contributions {
  query: string
  generated: string
  total: number
  repoCount: number
  first: string
  last: string
  repos: Contribution[]
}

export const contributions = raw as Contributions

/** github.com/search, with the same query the JSON was built from. */
export const contributionsSearchUrl = `https://github.com/search?q=${encodeURIComponent(
  contributions.query,
)}&type=pullrequests`

/** The owner half of "owner/repo". */
export function repoOwner(repo: string): string {
  return repo.split('/')[0]
}

/** The repo half, which is what anyone actually recognises. */
export function repoName(repo: string): string {
  return repo.split('/')[1] ?? repo
}
