import coverSizes from './cover-sizes.json'
import type { Domain, Medium, Practice, Status } from './taxonomy'

export interface Cover {
  /**
   * A tile under public/covers, generated by scripts/build-covers.py. Always
   * 1200x750 on the card's own ground, so every tile on the page shares one
   * aspect, one padding and one luminance ceiling.
   */
  src: string
  alt: string
  /**
   * Video covers are never autoplayed in a grid. The poster is what the card
   * shows; the video only loads once someone asks for it.
   */
  video?: string
}

export interface Entry {
  /** Stable URL segment. Also the React key and the filter deep-link target. */
  slug: string
  title: string
  /**
   * One or two sentences, and only what the linked artifact or Jay states.
   * Optional because the alternative, for work whose only published record is
   * its title, is to write a sentence that restates that title back at the
   * reader. That is filler at best and invention at worst.
   */
  summary?: string
  /**
   * ISO, either yyyy-mm or yyyy-mm-dd. Both sort correctly as strings, which
   * is the whole reason for the format.
   *
   * Use the day wherever it is actually known. Month precision put six things
   * in August 2026 with nothing to separate them, so they fell back to the
   * order they happen to sit in this file, and a storefront finished on the
   * 31st appeared below a hangout from the 12th.
   */
  date: string
  /**
   * When the work last changed, if it has changed since. The catalogue sorts
   * on this: something Jay came back to in May is more worth a visitor's time
   * than something finished in May and untouched since, and ordering purely by
   * first publication buries it.
   *
   * Only set where a source actually records it. For a repository that is the
   * last commit on the default branch. An article or a recording does not get
   * one, because nothing revised them.
   */
  updated?: string

  medium: Medium
  practices: Practice[]
  domains: Domain[]
  /** Free text. Displayed on detail pages, searched, never a filter chip. */
  tech?: string[]

  /**
   * Omitted where no usable source exists. Six entries are in that position:
   * four whose only thumbnail lived on YouTube's CDN, one exported at 246px,
   * one fully transparent. They render as a typographic tile rather than an
   * upscale or a hotlink, which stays sharp and cannot rot.
   */
  cover?: Cover
  /** Where the work itself lives. Omitted when the entry has no live home. */
  href?: string
  /** Set when there is a write-up on this site rather than only an outbound link. */
  detail?: string
  /** The organisation the work was done for or with. */
  org?: string

  status?: Status
  /** Surfaced on the home page and at the top of listings. */
  featured?: boolean
}

export function isExternal(href: string | undefined): boolean {
  return Boolean(href && /^https?:\/\//.test(href))
}

/**
 * "2025-04" -> "April 2025", "2026-08-31" -> "August 31, 2026".
 *
 * Kept out of the components so it stays consistent, and built from the parts
 * rather than parsed: `new Date('2026-08-31')` is UTC midnight, which in New
 * York is the evening of the 30th.
 */
export function formatDate(iso: string): string {
  const [year, month, day] = iso.split('-')
  if (!month) return year
  const date = new Date(Number(year), Number(month) - 1, Number(day ?? 1))
  return date.toLocaleDateString('en-US', {
    month: 'long',
    year: 'numeric',
    ...(day ? { day: 'numeric' } : {}),
  })
}

export function entryYear(iso: string): number {
  return Number(iso.split('-')[0])
}

/**
 * "2026-08-31" -> "Aug 2026". For cards, where the line already carries the
 * form and the organisation and the full date pushed it into an ellipsis. The
 * exact day is on the detail page, in the rail.
 */
export function formatDateShort(iso: string): string {
  const [year, month] = iso.split('-')
  if (!month) return year
  const date = new Date(Number(year), Number(month) - 1, 1)
  return date.toLocaleDateString('en-US', { month: 'short', year: 'numeric' })
}

/** What the catalogue sorts on: the last time this changed. */
export function entryRank(entry: { date: string; updated?: string }): string {
  return entry.updated ?? entry.date
}

/**
 * The normalised tile for a cover: /images/thing.png -> /covers/thing.webp.
 *
 * Entries name the original file, because that is the real artifact and the
 * detail page shows it at full fidelity and its own aspect. Cards and rows
 * want the generated tile instead, so they derive it here rather than the data
 * carrying two paths that can drift.
 *
 * scripts/build-covers.py writes every one of these. Six entries have no
 * cover at all and never reach this.
 */
export function tileFor(src: string): string {
  return `/covers/${coverStem(src)}.webp`
}

function coverStem(src: string): string {
  return src.replace(/^\/images\//, '').replace(/\.[^.]+$/, '')
}

/**
 * The original's real pixel dimensions, recorded by the same script that
 * builds the tiles. next/image needs them to reserve the right box, and the
 * detail page shows the artifact at its own aspect rather than forced into the
 * card's 16:10.
 */
export function coverSize(src: string): { width: number; height: number } {
  const found = (coverSizes as Record<string, number[]>)[coverStem(src)]
  // The fallback only fires if a cover is added without rerunning the script.
  return found ? { width: found[0], height: found[1] } : { width: 1600, height: 1000 }
}
