import Link from 'next/link'
import Image from 'next/image'
import { entryHref } from './EntryCard'
import { allEntries, isExternal, tileFor } from '@/lib/content'

/**
 * The work itself, across the top of the page.
 *
 * The first screen used to be a name, one sentence, six links and a rule, and
 * then a list. On a laptop that is most of a viewport of nothing, on the one
 * page where someone who just tapped a business card decides whether to keep
 * going.
 *
 * This is not decoration standing in for content: every tile is a real piece
 * of work, generated by the same script as every other tile, and every one of
 * them is a link to the thing itself. It runs off the right edge on purpose,
 * because the point being made is that there is a lot of it.
 *
 * Scrolls rather than animates. A strip that slides on its own is a thing to
 * wait for, and it takes the tile you were about to click away from you.
 */
export default function CoverBand() {
  const shown = allEntries.filter((e) => e.cover).slice(0, 24)

  return (
    <div className="cover-band">
      <ul className="cover-band-track">
        {shown.map((entry, i) => {
          const href = entryHref(entry)
          const tile = (
            <Image
              src={tileFor(entry.cover!.src)}
              alt={entry.cover!.alt}
              width={1200}
              height={750}
              priority={i < 4}
              sizes="264px"
              className="cover-band-img"
            />
          )
          return (
            <li key={entry.slug} className="cover-band-item">
              {href ? (
                <Link
                  href={href}
                  {...(isExternal(href)
                    ? { target: '_blank', rel: 'noopener noreferrer' }
                    : {})}
                  title={entry.title}
                >
                  {tile}
                </Link>
              ) : (
                tile
              )}
            </li>
          )
        })}
      </ul>
    </div>
  )
}
