import { Project } from './types'

export const projects: Project[] = [
  {
    title: 'Prompt2Flow',
    description:
      'AI platform for discovering, running, and publishing automated prompt workflows. Create single prompts or connect them in powerful automation flows for text generation, code, and image creation.',
    date: 'July 2025',
    image: '/images/prompt2flow.png',
    imageAlt: 'Prompt2Flow platform interface showing AI prompt discovery and automation workflows',
    link: 'https://www.prompt2flow.com',
    target: '_blank',
    skills: [
      'AI Development',
      'Prompt Engineering',
      'Automation',
      'Platform Development',
      'Next.js',
      'React',
      'TypeScript',
      'API Development',
      'Database Management',
      'UX Design',
      'Cloud Computing',
      'Authentication',
    ],
  },
  {
    title: 'Lilypad Pitch for IoTeX Competition',
    description:
      'Competitive pitch for IoTeX "Crypto\'s Got Talent" competition seeking $500,000 funding. Presentation now being used as core fundraising material for the Lilypad Network project.',
    date: 'May 2025',
    image: 'https://i.ytimg.com/vi/fa8RzuGRR7E/maxresdefault.jpg',
    imageAlt: 'Lilypad Network pitch presentation at IoTeX Crypto\'s Got Talent competition',
    link: 'https://www.youtube.com/watch?v=fa8RzuGRR7E',
    target: '_blank',
    skills: [
      'Public Speaking',
      'Fundraising',
      'AI Infrastructure',
      'Distributed Computing',
      'DePIN',
      'Dev Rel',
      'Pitch Deck Design',
      'Business Development',
      'Market Research',
      'Presentation Design',
    ],
  },
  {
    title: 'Threads, Tools, and Grok: Inside the Generative Future of X',
    description:
      'In-depth analysis of Grok AI\'s integration into X platform and its implications for the future of social media. Examines the intersection of AI tools and social networking.',
    date: 'April 2025',
    image: '/images/twitter-future.png',
    imageAlt: 'Medium article about Threads, Tools, and Grok generative AI on X platform',
    link: 'https://medium.com/@jonathan-albert/threads-tools-and-grok-inside-the-generative-future-of-x-f70c7e347f37',
    target: '_blank',
    skills: [
      'Technical Writing',
      'AI Analysis',
      'Social Media',
      'Generative AI',
      'Technology Trends',
      'Medium',
      'Content Creation',
      'Research',
      'Data Analysis',
      'Digital Publishing',
      'SEO',
      'Content Strategy',
    ],
  },

  {
    title: 'VibeCheck Community App',
    description:
      'Wiki-style platform comparing communities and suggesting collaboration opportunities. Built on Lilypad Network as part of weekly app development series showcasing rapid prototyping.',
    date: 'April 2025',
    image: '/images/vibecheck.png',
    imageAlt: 'VibeCheck Community App screenshot showing community comparison interface',
    link: 'https://vibecheck-app.vercel.app/',
    target: '_blank',
    skills: [
      'Next.js',
      'React',
      'AI Development',
      'Lilypad',
      'Rapid Prototyping',
      'Community Building',
      'TypeScript',
      'JavaScript',
      'API Integration',
      'Database Design',
      'Full-Stack Development',
      'Vercel',
    ],
  },
  {
    title: 'Web3 Game Mechanic Generator',
    description: 'Custom GPT transforming smart contract methods into creative game mechanics and demo ideas. Bridges the gap between blockchain technology and game development innovation.',
    date: 'April 2025',
    image: '/images/mechanic-generator.png',
    imageAlt: 'Screenshot of Web3 Game Mechanic Generator GPT interface',
    link: 'https://chatgpt.com/g/g-67e71d3f566c81918471509fb5b3b63b-web3-game-mechanic-generator',
    target: '_blank',
    skills: [
      'Generative AI',
      'Smart Contracts',
      'Game Design',
      'Web3',
      'Blockchain Gaming',
      'Technical Education',
      'Dev Rel',
      'GPT Development',
      'Prompt Engineering',
      'OpenAI API',
      'Documentation',
      'Educational Content',
    ],
  },
  {
    title: 'Building RAG Agents on Lilypad',
    description:
      'Live demonstration building Retrieval-Augmented Generation agents on Lilypad Network. Shows how AI agents can access and reason with external knowledge sources in decentralized environments.',
    date: 'March 2025',
    image: 'https://i.ytimg.com/vi/I-_9yO4wdig/maxresdefault.jpg',
    imageAlt: 'RAG Agents on Lilypad Network demo thumbnail',
    link: 'https://www.youtube.com/watch?v=I-_9yO4wdig',
    target: '_blank',
    skills: [
      'AI Development',
      'RAG Agents',
      'Live Demo',
      'Decentralized Computing',
      'Technical Education',
      'Public Speaking',
      'Workshop Facilitation',
      'Dev Rel',
      'Python',
      'Machine Learning',
      'Vector Databases',
      'Embeddings',
    ],
  },
  {
    title: 'Sir Croaksworth\'s Roast DApp',
    description:
      'Humorous DApp featuring a pretentious frog banker who roasts crypto wallet transactions. Enter any wallet address for brutally honest feedback on investment choices and trading history.',
    date: 'March 2025',
    image: '/images/roast.png',
    imageAlt: 'Screenshot of Sir Croaksworth, a frog with a top hat who roasts your crypto wallet transactions',
    link: 'https://roast-app-delta.vercel.app/',
    target: '_blank',
    skills: [
      'Web3',
      'DApp Development',
      'Next.js',
      'Blockchain',
      'Cryptocurrency',
      'UI Design',
      'Transaction Analysis',
      'React',
      'TypeScript',
      'Wallet Integration',
      'Ethereum',
      'Comedy Writing',
    ],
  },
  {
    title: 'CollabHubs Community Spotlight',
    description: 'Featured as Builder of the Month in CollabHubs Community Spotlight recognizing contributions to Web3 development, AI integration, and blockchain gaming projects.',
    date: 'March 2025',
    image: '/images/collabhub.png',
    imageAlt: 'CollabHubs Community Spotlight article featuring Jay Albert as Builder of the Month',
    link: 'https://medium.com/@_WEB3M_/collabhubs-community-spotlight-builder-of-the-month-a0e639e763cc',
    target: '_blank',
    skills: [
      'Web3',
      'Community Building',
      'AI Development',
      'Blockchain Gaming',
      'Dev Rel',
      'Content Creation',
      'Technical Education',
      'Decentralized Computing',
      'Medium',
      'Industry Recognition',
      'Personal Branding',
    ],
  },
  {
    title: 'Lilypad Pitch at Crypto\'s Got Talent',
    description:
      'Competitive pitch presentation for Crypto\'s Got Talent hosted by IoTeX, competing for $500,000 funding. Showcased decentralized AI infrastructure platform to panel of industry judges.',
    date: 'March 2025',
    image: 'https://i.ytimg.com/vi/qUMOPe56vqI/maxresdefault.jpg',
    imageAlt: 'Lilypad Network pitch at Crypto\'s Got Talent competition thumbnail',
    link: 'https://youtu.be/qUMOPe56vqI',
    target: '_blank',
    skills: [
      'Public Speaking',
      'AI Infrastructure',
      'Web3',
      'Dev Rel',
      'Decentralized Computing',
      'Fundraising',
      'Pitch Presentations',
      'Competition',
      'IoTeX',
      'Investment Pitching',
    ],
  },
  {
    title: 'Lilypad Frontend Workshop',
    description:
      'Live workshop demonstrating frontend development for Lilypad Network. Helped developers create interfaces for decentralized compute networks through hands-on coding sessions.',
    date: 'February 2025',
    image: 'https://i.ytimg.com/vi/6VuEM4l5_oo/maxresdefault.jpg',
    imageAlt: 'Lilypad Network Frontend Workshop Thumbnail',
    link: 'https://www.youtube.com/watch?v=6VuEM4l5_oo',
    target: '_blank',
    skills: [
      'Public Speaking',
      'Technical Education',
      'Next.js',
      'Lilypad Network',
      'Decentralized Computing',
      'Frontend Development',
      'Workshop Facilitation',
      'React',
      'TypeScript',
      'Live Coding',
      'Developer Training',
    ],
  },
  {
    title: 'Twitter Spaces on Gaming & AI',
    description:
      'Regular speaking engagements in Twitter Spaces discussing gaming\'s future, AI integration, and Web3 development. Panel discussions on blockchain gaming trends and industry innovations.',
    date: 'February 2025',
    image: '/images/game7.jpeg',
    imageAlt: 'Game7 Twitter Space on AI Agents in Gaming',
    link: './spaces',
    skills: [
      'Public Speaking',
      'AI in Gaming',
      'Web3',
      'Game Development',
      'Blockchain Gaming',
      'Community Engagement',
      'Industry Trends',
      'Twitter Spaces',
      'Panel Discussion',
      'Thought Leadership',
      'Gaming Industry',
    ],
  },
  {
    title: 'The Future of Gaming Series',
    description:
      'Regular live streaming series focused on blockchain gaming, game development, and Web3 technology. Educational content covering Unity integration and smart contract implementation.',
    date: 'January 2025',
    image: '/images/Moddio.png',
    imageAlt: 'Stream banner featuring the Moddio game engine interface',
    link: './streams',
    skills: [
      'Blockchain Gaming',
      'Game Development',
      'Web3',
      'Unity',
      'Smart Contracts',
      'Live Streaming',
      'Dev Rel',
      'Content Creation',
      'Public Speaking',
      'Twitch',
      'YouTube',
      'Community Building',
    ],
  },
  {
    title: 'Rock Paper Scissors Workshop',
    description:
      'Interactive workshop teaching blockchain-powered game development using Unity and Chainlink VRF. Hands-on tutorial covering randomness implementation and smart contract integration.',
    date: 'December 2024',
    image: '/images/rps-workshop.jpeg',
    imageAlt: 'Rock Paper Scissors Workshop Tutorial Screenshot',
    link: 'https://www.youtube.com/live/V9hxpnm-zEc?si=TLQBMCemCBTqvX6x&t=1',
    target: '_blank',
    skills: [
      'Unity',
      'Blockchain Gaming',
      'Chainlink VRF',
      'Smart Contracts',
      'Game Development',
      'Dev Rel',
      'Technical Education',
      'Workshop Facilitation',
    ],
  },
  {
    title: 'On-Chain Lootboxes at GDC',
    description:
      'Technical demonstration of on-chain lootboxes presented at Game Developers Conference. Showcased innovative blockchain gaming mechanics to industry professionals and developers.',
    date: 'April 2024',
    image: '/images/loot-gdc.png',
    imageAlt: 'ChainSafe GDC Lootboxes presentation',
    link: 'https://blog.chainsafe.io/onchain-lootboxes-gdc/',
    target: '_blank',
    skills: [
      'Blockchain Gaming',
      'Smart Contracts',
      'Solidity',
      'Web3',
      'Technical Writing',
      'Documentation',
      'Public Speaking',
      'Game Development',
    ],
  },
  {
    title: 'Lilypad Frontend Guide',
    description:
      'Comprehensive developer guide for setting up and customizing Lilypad Network frontends. Improved developer experience through detailed documentation and code examples.',
    date: 'December 2023',
    image: '/images/lilypad-frontend.avif',
    imageAlt:
      'Screenshot of a code editor showing React components for Lilypad Network',
    link: 'https://blog.lilypadnetwork.org/setting-up-your-lilypad-front-end',
    target: '_blank',
    skills: [
      'Technical Writing',
      'Documentation',
      'React',
      'Next.js',
      'TypeScript',
      'Frontend Development',
      'UI Development',
      'Git',
      'Dev Rel',
    ],
  },
  {
    title: 'Lilypad Network',
    description:
      'Contributed to the development of a decentralized compute network, focusing on improving user experience and documentation.',
    date: 'December 2023',
    image: '/images/lilypad.avif',
    imageAlt: 'Lilypad Network logo showing a modern, stylized lily pad',
    link: 'https://blog.lilypadnetwork.org/hop-into-the-future-with-lilypad-the-distributed-compute-network',
    target: '_blank',
    skills: [
      'Documentation',
      'Distributed Computing',
      'Blockchain',
      'Linux',
      'Content Creation',
      'Dev Rel',
      'Technical Writing',
    ],
  },
  {
    title: 'The Machine Dreams',
    description:
      'An art project that uses AI to generate art every hour based on what is trending on Google in the U.S.',
    date: 'October 2023',
    image: '/images/machine_dream.jpg',
    imageAlt:
      'A circular logo with an M in the middle and colorful clouds at the bottom.',
    link: 'https://www.themachinedreams.com/about',
    target: '_blank',
    skills: [
      'Python',
      'Typescript',
      'Twitter API',
      'Stability AI SDK',
      'Thirdweb SDK',
      'IPFS',
      'NFT.storage',
      'Solidity',
      'Openzeppelin',
      'Sepolia',
      'Ethereum',
      'Opensea',
      'Chainlink',
      'Google Cloud Platform',
    ],
  },
  {
    title: 'Web2 to Web3 Game Development Workshop',
    description:
      'Led a hands-on workshop at ETHDenver demo how to transform a traditional game into a blockchain-enabled experience.',
    date: 'February 2023',
    image: '/images/ethdenver-workshop.avif',
    imageAlt: 'ETHDenver Workshop presentation screenshot',
    link: 'https://www.youtube.com/watch?v=c_gONMVIH8o&t=0s',
    target: '_blank',
    skills: [
      'Game Development',
      'Web3',
      'Smart Contracts',
      'Public Speaking',
      'Technical Education',
      'Dev Rel',
      'Live Coding',
      'Workshop Facilitation',
      'Blockchain',
    ],
  },
  {
    title: 'Mix3d Clothing',
    description: 'A clothing brand concept from the Mix3d community.',
    date: 'December 2022',
    image: '/images/shirt.png',
    imageAlt:
      'A 3D model of a black shirt with the Mix3d community logo on the front.',
    link: './mix3d-clothing',
    skills: [
      'Moralis',
      'Meta Mask',
      'Goerli Test Network',
      'Javascript',
      'HTML',
      'CSS',
      'Figma',
      'Clo3d',
      'Spark AR',
      'Augmented Reality',
      'Vectary',
      'Magica Voxel',
      'Github',
    ],
  },
  {
    title: 'Understanding ENS',
    description:
      'A guide explaining the Ethereum Name Service (ENS), its parallels with DNS, and its importance for Web3 adoption.',
    date: 'October 2022',
    image: '/images/ens-guide.png',
    imageAlt: 'Visualization comparing DNS and ENS domain systems',
    link: 'https://mirror.xyz/jay-albert.eth/VhAJt973aV6vHZ-0-oMqxPML52f-unYe5rE1h0TsmaU',
    target: '_blank',
    skills: [
      'Web3',
      'ENS',
      'Blockchain',
      'Technical Writing',
      'Domain Systems',
      'Ethereum',
      'Educational Content',
      'Content Creation',
    ],
  },
  {
    title: 'Exploring Web3 Finance',
    description:
      'Snapshots of my experiences in cryptocurrency investing using DeFi tools and working with TradFi organizations.',
    date: 'October 2022',
    image: '/images/tokensets.png',
    imageAlt:
      'Two blue circle overlaping eachother with the top circle containing a fade on the right side and the bottom circle containing a fade on the left side. The fades make the circles appear vaguely in the shape of an S',
    link: './tokensets',
    skills: [
      'Tokensets',
      'Meta Mask',
      'Polygon',
      'DeFi',
      'TradFi',
      'Indexes',
      'Investment Analysis',
      'Writing',
    ],
  },
  {
    title: 'Invisible Maze Game',
    description:
      'An invisible maze game to onboard users to Metamask and Decentraland.',
    date: 'January 2022',
    image: '/images/invisible-maze.png',
    imageAlt: 'A view of an invisible maze game made in Decentraland',
    link: './invisible-maze-game',
    skills: [
      'Decentraland',
      'Meta Mask',
      'Ethereum Network',
      'Etherscan',
      'Notion',
      'Game Design',
    ],
  },
  {
    title: 'Mix3d',
    description:
      'Mix3d is a community connecting, organizing, and building on Web 3.',
    date: 'January 2022',
    image: '/images/mix3d.png',
    imageAlt: 'A logo of circles in a spiral with varrying colors',
    link: './mix3d',
    skills: [
      'Notion',
      'Discord',
      'Meta Mask',
      'Partybid',
      'Mirror',
      'Community Management',
      'Consulting',
      'Project Management',
      'Educational Content',
    ],
  },
  {
    title: 'Hunting for Art',
    description:
      'A detailed exploration of NFT trading safety, following my experience of safely executing a peer-to-peer NFT swap of Smilesssvrs artwork using SudoSwap.',
    date: 'December 2021',
    image: '/images/hunting-art.webp',
    imageAlt:
      'Screenshot of Smilesssvrs NFT artwork from the trading experience',
    link: 'https://jonathan-albert.medium.com/hunting-for-art-b804d2f55dbb',
    target: '_blank',
    skills: [
      'NFTs',
      'Web3 Security',
      'DeFi',
      'Digital Art',
      'Smart Contracts',
      'Technical Writing',
      'Blockchain',
      'Community Building',
    ],
  },
  {
    title: 'Crypto Banking Guide',
    description:
      'Authored a comprehensive guide on maximizing interest earnings through crypto banking platforms and stablecoins.',
    date: 'May 2021',
    image: '/images/crypto-banking.jpeg',
    imageAlt:
      'Graph showing crypto interest rates compared to traditional banking',
    link: 'https://jonathan-albert.medium.com/earn-more-interest-with-crypto-banking-4657bb167a32',
    target: '_blank',
    skills: [
      'DeFi',
      'Crypto Banking',
      'Technical Writing',
      'Yield Farming',
      'Research',
      'Financial Education',
      'Content Creation',
    ],
  },
  {
    title: 'Werewolf',
    description: 'A social deduction game utilizing webcams on a browser.',
    date: 'September 2020',
    image: '/images/werewolf.png',
    imageAlt:
      'A sign in screen with the word Werewolf at the top in a font that looks like bloody letters',
    link: './werewolf',
    skills: [
      'Javascript',
      'React',
      'JSX',
      'HTML',
      'CSS',
      'Dafont',
      'Material UI',
      'AniJS',
      'Express',
      'Morgan',
      'Sequelize',
      'Firebase',
      'Twilio',
      'Github',
      'Game Design',
    ],
  },
  {
    title: 'Grace Potter',
    description: 'An e-commerce website selling handmade pottery.',
    date: 'August 2020',
    image: '/images/grace-potter.png',
    imageAlt: 'An icon of a pottery vase',
    link: './grace-potter',
    skills: [
      'Javascript',
      'React',
      'JSX',
      'HTML',
      'CSS',
      'Redux',
      'Reactstrap',
      'WebSocket',
      'Express',
      'Sequelize',
      'Axios',
      'PostgreSQL',
      'Postman',
      'Nodemailer',
      'Stripe',
      'Github',
    ],
  },
  {
    title: 'Mobile Vendor',
    description: 'A platform to connect mobile vendors to potential customers.',
    date: 'August 2020',
    image: '/images/mobile-vendor.png',
    imageAlt:
      'A smart phone overlayed on top of a map with icons for mobile vendors',
    link: './mobile-vendor',
    skills: [
      'Javascript',
      'React Native',
      'MapView',
      'Expo',
      'Redux',
      'HTML',
      'CSS',
      'Firebase',
      'Github',
      'Mobile Development',
      'Geolocation',
      'State Management',
      'NoSQL',
      'Cloud Services',
      'Real-time Updates',
      'UI/UX Design',
    ],
  },
  {
    title: 'Thought Card',
    description:
      'Augmented Reality (AR) allows developers to pack information into images. Business cards can now contain links, videos, 3D objects, scenes, games, and more.',
    date: 'April 2020',
    image: '/images/thought-card.png',
    imageAlt:
      "A blue business card with a quote that reads 'The convential mind is passive - it consumes information and regurgitates it in familiar forms. The dimensional mind is active. Transforming everything it digests into something new and original, creating instead of consuming' by Robert Greene from the book Mastery on page 177.",
    link: './thought-card',
    skills: [
      'Unity',
      'Vuforia',
      'C#',
      'Augmented Reality',
      'Image Recognition',
      'Interactive Design',
      'Mobile AR',
      'UI/UX Design',
      'Digital Content Creation',
      'Mixed Reality',
    ],
  },
  {
    title: 'Wix',
    description:
      'A stint as a freelancer for Wix websites fueled by word-of-mouth recommendations.',
    date: 'March 2020',
    image: '/images/wix.png',
    imageAlt: 'The wix website logo',
    link: './wix',
    skills: [
      'Wix',
      'UI',
      'Client Relations',
      'Business Analysis',
      'Project Management',
      'Budgeting',
      'Web Design',
      'Responsive Design',
      'Analytics',
      'CMS',
      'Client Communication',
    ],
  },
  {
    title: 'Blotto',
    description:
      'A drinking card game that served as a proof of concept for launching applications using Unity on the Google Play store.',
    date: 'January 2020',
    image: '/images/blotto.png',
    imageAlt:
      "A flat image of a body with its head in a toilet and the words 'Blotto' written under the image.",
    link: './blotto',
    skills: [
      'Unity',
      'C#',
      'UI',
      'Game Design',
      'Animation',
      'Sound',
      'Project Management',
      'Game Testing',
      'Mobile Game Development',
      'Google Play Store',
      'App Publishing',
      'Asset Management',
    ],
  },
  {
    title: 'LiveIn',
    description:
      'LiveIn was a real estate brokerage that utilized augmented reality to engage with potential clients.',
    date: 'October 2019',
    image: '/images/livein.png',
    imageAlt:
      'A logo of a leaf that has lines across it similar to that of a circuit board',
    link: './livein',
    skills: [
      'Project Management',
      'Business Analysis',
      'UX',
      'Trello',
      'Real Estate',
      'Augmented Reality',
      'Product Strategy',
      'Stakeholder Management',
    ],
  },
  {
    title: 'Augmented Piano Lessons',
    description:
      'The future of learning how to play music will involve projections that augment the instrument to gamify the learning process.',
    date: 'December 2017',
    image: '/images/ar-piano-lessons.png',
    imageAlt: 'Piano keys on with a background of musical notes',
    link: './ar-piano-lessons',
    skills: [
      'Unity',
      'C#',
      'Augmented Reality',
      'Animation',
      'Sound',
      'Interactive Learning',
      'Music Education',
      'Mixed Reality',
      'User Experience Design',
    ],
  },
  {
    title: 'Traffic Jam VR',
    description:
      'Traffic Jam VR is the product of a 3-day virtual reality game jam where professionals from various backgrounds came together to create virtual reality games.',
    date: 'August 2017',
    image: '/images/traffic-jam-vr.png',
    imageAlt: 'A low poly image of a street corner',
    link: './traffic-jam-vr',
    skills: [
      'Unity',
      'C#',
      'Virtual Reality',
      'Game Design',
      'Scene Design',
      'Level Design',
      'Rapid Prototyping',
      'Game Jam',
      'Team Collaboration',
    ],
  },
  {
    title: 'The Fourth Branch',
    description:
      'The Fourth Branch summarizes bills debated in Congress and allows users to vote on the summaries and compare their votes to those of their Congressmen.',
    date: 'January 2017',
    image: '/images/the-fourth-branch.png',
    imageAlt:
      'A logo with two parallel blue lines at the forefront and a red line in the background in the shape of a staple',
    link: './the-fourth-branch',
    skills: [
      'Product Management',
      'Project Management',
      'Business Analysis',
      'Basecamp',
      'Slack',
      'UX',
      'QA',
      'Mockups',
      'Marketing',
      'Content Creation',
      'Social Media Management',
      'Event Planning',
      'Community Engagement',
    ],
  },
  {
    title: 'Memorial Website',
    description:
      'There are many ways to remember a lost relative, and with modern technology, we can immortalize their experiences.',
    date: 'October 2014',
    image: '/images/memorial-website.jpg',
    imageAlt:
      "A painted mural of a person with a hat, and the word 'Ferle' written under it",
    link: './memorial-website',
    skills: [
      'Wix',
      'UX',
      'UI',
      'Web Design',
      'Responsive Design',
      'Digital Preservation',
      'User-Centered Design',
    ],
  },
  {
    title: 'Customizable Phone Case',
    description:
      'In the early 2010s, the iPhone had a small battery, and owners were seeking to protect their phones while customizing the look. The customizable phone case sought to provide a dynamic look and improve battery life for iPhones.',
    date: 'July 2014',
    image: '/images/custom-phone-case.png',
    imageAlt: 'A mechanical engineering mockup of an old iphone with a case',
    link: './customizable-phone-case',
    skills: [
      'Product Management',
      'Project Management',
      'Hardware Design',
      'Product Design',
      'Prototyping',
      'Consumer Electronics',
    ],
  },
]

export const getAllSkills = (): string[] => {
  const skillsSet = new Set<string>()
  projects.forEach((project) => {
    project.skills.forEach((skill) => skillsSet.add(skill))
  })
  return Array.from(skillsSet)
}

export const filterProjects = (
  projects: Project[],
  selectedSkills: string[]
): Project[] => {
  if (selectedSkills.length === 0) return projects
  return projects.filter((project) =>
    selectedSkills.some((skill) => project.skills.includes(skill))
  )
}
