import { Project } from './types'

export const projects: Project[] = [
  {
    title: 'Lilypad Network Frontend Workshop',
    description:
      'Live workshop demonstrating how to build a frontend on top of the Lilypad Network, helping developers create interfaces for a decentralized compute network.',
    date: 'February 2025',
    image: 'https://i.ytimg.com/vi/6VuEM4l5_oo/maxresdefault.jpg',
    imageAlt: 'Lilypad Network Frontend Workshop Thumbnail',
    link: 'https://www.youtube.com/watch?v=6VuEM4l5_oo',
    target: '_blank',
    skills: [
      'Public Speaking',
      'Technical Education',
      'Next.js',
      'Lilypad Network',
      'Decentralized Computing',
      'Frontend Development',
      'Workshop Facilitation',
    ],
  },
  {
    title: 'Twitter Spaces on Gaming & AI',
    description:
      'Regular speaker in Twitter Spaces discussing the future of gaming, AI integration, and Web3 development.',
    date: 'February 2025',
    image: '/images/game7.jpeg',
    imageAlt: 'Game7 Twitter Space on AI Agents in Gaming',
    link: './spaces',
    skills: [
      'Public Speaking',
      'AI in Gaming',
      'Web3',
      'Game Development',
      'Blockchain Gaming',
      'Community Engagement',
      'Technical Education',
      'Industry Trends',
    ],
  },
  {
    title: 'The Future of Gaming Series',
    description:
      'Host regular live streams focused on blockchain gaming, game development, and Web3 technology.',
    date: 'January 2025',
    image: '/images/Moddio.png',
    imageAlt: 'Stream banner featuring the Moddio game engine interface',
    link: './streams',
    skills: [
      'Blockchain Gaming',
      'Game Development',
      'Web3',
      'Unity',
      'Smart Contracts',
      'Live Streaming',
      'Developer Relations',
      'Content Creation',
      'Public Speaking',
    ],
  },
  {
    title: 'Rock Paper Scissors Workshop',
    description:
      'Led an interactive workshop teaching students how to build a blockchain-powered Rock Paper Scissors game using Unity and Chainlink VRF.',
    date: 'December 2024',
    image: '/images/rps-workshop.jpeg',
    imageAlt: 'Rock Paper Scissors Workshop Tutorial Screenshot',
    link: 'https://www.youtube.com/live/V9hxpnm-zEc?si=TLQBMCemCBTqvX6x&t=1',
    target: '_blank',
    skills: [
      'Unity',
      'Blockchain Gaming',
      'Chainlink VRF',
      'Smart Contracts',
      'Game Development',
      'Technical Education',
      'Workshop Facilitation',
      'Developer Relations',
    ],
  },
  {
    title: 'On-Chain Lootboxes at GDC',
    description:
      'Developed and presented a technical demonstration of on-chain lootboxes at the Game Developers Conference (GDC).',
    date: 'April 2024',
    image: '/images/loot-gdc.png',
    imageAlt: 'ChainSafe GDC Lootboxes presentation',
    link: 'https://blog.chainsafe.io/onchain-lootboxes-gdc/',
    target: '_blank',
    skills: [
      'Blockchain Gaming',
      'Smart Contracts',
      'Solidity',
      'Web3',
      'Technical Writing',
      'Documentation',
      'Public Speaking',
      'Game Development',
    ],
  },
  {
    title: 'Lilypad Frontend Guide',
    description:
      'Created a comprehensive guide for developers to set up and customize their Lilypad Network frontend, improving the developer experience for the platform.',
    date: 'December 2023',
    image: '/images/lilypad-frontend.avif',
    imageAlt:
      'Screenshot of a code editor showing React components for Lilypad Network',
    link: 'https://blog.lilypadnetwork.org/setting-up-your-lilypad-front-end',
    target: '_blank',
    skills: [
      'Technical Writing',
      'Documentation',
      'React',
      'Next.js',
      'TypeScript',
      'Frontend Development',
      'UI Development',
      'Git',
      'Developer Relations',
    ],
  },
  {
    title: 'Lilypad Network',
    description:
      'Contributed to the development of a decentralized compute network, focusing on improving user experience and documentation.',
    date: 'December 2023',
    image: '/images/lilypad.avif',
    imageAlt: 'Lilypad Network logo showing a modern, stylized lily pad',
    link: 'https://blog.lilypadnetwork.org/hop-into-the-future-with-lilypad-the-distributed-compute-network',
    target: '_blank',
    skills: [
      'Documentation',
      'Distributed Computing',
      'Blockchain',
      'Linux',
      'Content Creation',
      'Developer Relations',
      'Technical Writing',
    ],
  },
  {
    title: 'The Machine Dreams',
    description:
      'An art project that uses AI to generate art every hour based on what is trending on Google in the U.S.',
    date: 'October 2023',
    image: '/images/machine_dream.jpg',
    imageAlt:
      'A circular logo with an M in the middle and colorful clouds at the bottom.',
    link: 'https://www.themachinedreams.com/about',
    target: '_blank',
    skills: [
      'Python',
      'Typescript',
      'Twitter API',
      'Stability AI SDK',
      'Thirdweb SDK',
      'IPFS',
      'NFT.storage',
      'Solidity',
      'Openzeppelin',
      'Sepolia',
      'Ethereum',
      'Opensea',
      'Chainlink',
      'Google Cloud Platform',
    ],
  },
  {
    title: 'Web2 to Web3 Game Development Workshop',
    description:
      'Led a hands-on workshop at ETHDenver demonstrating how to transform a traditional game into a blockchain-enabled experience.',
    date: 'February 2023',
    image: '/images/ethdenver-workshop.avif',
    imageAlt: 'ETHDenver Workshop presentation screenshot',
    link: 'https://www.youtube.com/watch?v=c_gONMVIH8o&t=0s',
    target: '_blank',
    skills: [
      'Game Development',
      'Web3',
      'Smart Contracts',
      'Public Speaking',
      'Technical Education',
      'Live Coding',
      'Workshop Facilitation',
      'Blockchain',
      'Developer Relations',
    ],
  },
  {
    title: 'Mix3d Clothing',
    description: 'A clothing brand concept from the Mix3d community.',
    date: 'December 2022',
    image: '/images/shirt.png',
    imageAlt:
      'A 3D model of a black shirt with the Mix3d community logo on the front.',
    link: './mix3d-clothing',
    skills: [
      'Moralis',
      'Meta Mask',
      'Goerli Test Network',
      'Javascript',
      'HTML',
      'CSS',
      'Figma',
      'Clo3d',
      'Spark AR',
      'Augmented Reality',
      'Vectary',
      'Magica Voxel',
      'Github',
    ],
  },
  {
    title: 'Understanding ENS',
    description:
      'A guide explaining the Ethereum Name Service (ENS), its parallels with DNS, and its importance for Web3 adoption.',
    date: 'October 2022',
    image: '/images/ens-guide.png',
    imageAlt: 'Visualization comparing DNS and ENS domain systems',
    link: 'https://mirror.xyz/jay-albert.eth/VhAJt973aV6vHZ-0-oMqxPML52f-unYe5rE1h0TsmaU',
    target: '_blank',
    skills: [
      'Web3',
      'ENS',
      'Blockchain',
      'Technical Writing',
      'Domain Systems',
      'Ethereum',
      'Educational Content',
      'Content Creation',
    ],
  },
  {
    title: 'Exploring Web3 Finance',
    description:
      'Snapshots of my experiences in cryptocurrency investing using DeFi tools and working with TradFi organizations.',
    date: 'October 2022',
    image: '/images/tokensets.png',
    imageAlt:
      'Two blue circle overlaping eachother with the top circle containing a fade on the right side and the bottom circle containing a fade on the left side. The fades make the circles appear vaguely in the shape of an S',
    link: './tokensets',
    skills: [
      'Tokensets',
      'Meta Mask',
      'Polygon',
      'DeFi',
      'TradFi',
      'Indexes',
      'Investment Analysis',
      'Writing',
    ],
  },
  {
    title: 'Invisible Maze Game',
    description:
      'An invisible maze game to onboard users to Metamask and Decentraland.',
    date: 'January 2022',
    image: '/images/invisible-maze.png',
    imageAlt: 'A view of an invisible maze game made in Decentraland',
    link: './invisible-maze-game',
    skills: [
      'Decentraland',
      'Meta Mask',
      'Ethereum Network',
      'Etherscan',
      'Notion',
      'Game Design',
    ],
  },
  {
    title: 'Mix3d',
    description:
      'Mix3d is a community connecting, organizing, and building on Web 3.',
    date: 'January 2022',
    image: '/images/mix3d.png',
    imageAlt: 'A logo of circles in a spiral with varrying colors',
    link: './mix3d',
    skills: [
      'Notion',
      'Discord',
      'Meta Mask',
      'Partybid',
      'Mirror',
      'Community Management',
      'Consulting',
      'Project Management',
      'Educational Content',
    ],
  },
  {
    title: 'Hunting for Art',
    description:
      'A detailed exploration of NFT trading safety, following my experience of safely executing a peer-to-peer NFT swap of Smilesssvrs artwork using SudoSwap.',
    date: 'December 2021',
    image: '/images/hunting-art.webp',
    imageAlt:
      'Screenshot of Smilesssvrs NFT artwork from the trading experience',
    link: 'https://jonathan-albert.medium.com/hunting-for-art-b804d2f55dbb',
    target: '_blank',
    skills: [
      'NFTs',
      'Web3 Security',
      'DeFi',
      'Digital Art',
      'Smart Contracts',
      'Technical Writing',
      'Blockchain',
      'Community Building',
    ],
  },
  {
    title: 'Crypto Banking Guide',
    description:
      'Authored a comprehensive guide on maximizing interest earnings through crypto banking platforms and stablecoins.',
    date: 'May 2021',
    image: '/images/crypto-banking.jpeg',
    imageAlt:
      'Graph showing crypto interest rates compared to traditional banking',
    link: 'https://jonathan-albert.medium.com/earn-more-interest-with-crypto-banking-4657bb167a32',
    target: '_blank',
    skills: [
      'DeFi',
      'Crypto Banking',
      'Technical Writing',
      'Yield Farming',
      'Research',
      'Financial Education',
      'Content Creation',
    ],
  },
  {
    title: 'Werewolf',
    description: 'A social deduction game utilizing webcams on a browser.',
    date: 'September 2020',
    image: '/images/werewolf.png',
    imageAlt:
      'A sign in screen with the word Werewolf at the top in a font that looks like bloody letters',
    link: './werewolf',
    skills: [
      'Javascript',
      'React',
      'JSX',
      'HTML',
      'CSS',
      'Dafont',
      'Material UI',
      'AniJS',
      'Express',
      'Morgan',
      'Sequelize',
      'Firebase',
      'Twilio',
      'Github',
      'Game Design',
    ],
  },
  {
    title: 'Grace Potter',
    description: 'An e-commerce website selling handmade pottery.',
    date: 'August 2020',
    image: '/images/grace-potter.png',
    imageAlt: 'An icon of a pottery vase',
    link: './grace-potter',
    skills: [
      'Javascript',
      'React',
      'JSX',
      'HTML',
      'CSS',
      'Redux',
      'Reactstrap',
      'WebSocket',
      'Express',
      'Sequelize',
      'Axios',
      'PostgreSQL',
      'Postman',
      'Nodemailer',
      'Stripe',
      'Github',
    ],
  },
  {
    title: 'Mobile Vendor',
    description: 'A platform to connect mobile vendors to potential customers.',
    date: 'August 2020',
    image: '/images/mobile-vendor.png',
    imageAlt:
      'A smart phone overlayed on top of a map with icons for mobile vendors',
    link: './mobile-vendor',
    skills: [
      'Javascript',
      'React Native',
      'MapView',
      'Expo',
      'Redux',
      'HTML',
      'CSS',
      'Firebase',
      'Github',
      'Mobile Development',
      'Geolocation',
      'State Management',
      'NoSQL',
      'Cloud Services',
      'Real-time Updates',
      'UI/UX Design',
    ],
  },
  {
    title: 'Thought Card',
    description:
      'Augmented Reality (AR) allows developers to pack information into images. Business cards can now contain links, videos, 3D objects, scenes, games, and more.',
    date: 'April 2020',
    image: '/images/thought-card.png',
    imageAlt:
      "A blue business card with a quote that reads 'The convential mind is passive - it consumes information and regurgitates it in familiar forms. The dimensional mind is active. Transforming everything it digests into something new and original, creating instead of consuming' by Robert Greene from the book Mastery on page 177.",
    link: './thought-card',
    skills: [
      'Unity',
      'Vuforia',
      'C#',
      'Augmented Reality',
      'Image Recognition',
      'Interactive Design',
      'Mobile AR',
      'UI/UX Design',
      'Digital Content Creation',
      'Mixed Reality',
    ],
  },
  {
    title: 'Wix',
    description:
      'A stint as a freelancer for Wix websites fueled by word-of-mouth recommendations.',
    date: 'March 2020',
    image: '/images/wix.png',
    imageAlt: 'The wix website logo',
    link: './wix',
    skills: [
      'Wix',
      'UI',
      'Client Relations',
      'Business Analysis',
      'Project Management',
      'Budgeting',
      'Web Design',
      'Responsive Design',
      'Analytics',
      'CMS',
      'Client Communication',
    ],
  },
  {
    title: 'Blotto',
    description:
      'A drinking card game that served as a proof of concept for launching applications using Unity on the Google Play store.',
    date: 'January 2020',
    image: '/images/blotto.png',
    imageAlt:
      "A flat image of a body with its head in a toilet and the words 'Blotto' written under the image.",
    link: './blotto',
    skills: [
      'Unity',
      'C#',
      'UI',
      'Game Design',
      'Animation',
      'Sound',
      'Project Management',
      'Game Testing',
      'Mobile Game Development',
      'Google Play Store',
      'App Publishing',
      'Asset Management',
    ],
  },
  {
    title: 'LiveIn',
    description:
      'LiveIn was a real estate brokerage that utilized augmented reality to engage with potential clients.',
    date: 'October 2019',
    image: '/images/livein.png',
    imageAlt:
      'A logo of a leaf that has lines across it similar to that of a circuit board',
    link: './livein',
    skills: [
      'Project Management',
      'Business Analysis',
      'UX',
      'Trello',
      'Real Estate',
      'Augmented Reality',
      'Product Strategy',
      'Stakeholder Management',
    ],
  },
  {
    title: 'Augmented Piano Lessons',
    description:
      'The future of learning how to play music will involve projections that augment the instrument to gamify the learning process.',
    date: 'December 2017',
    image: '/images/ar-piano-lessons.png',
    imageAlt: 'Piano keys on with a background of musical notes',
    link: './ar-piano-lessons',
    skills: [
      'Unity',
      'C#',
      'Augmented Reality',
      'Animation',
      'Sound',
      'Interactive Learning',
      'Music Education',
      'Mixed Reality',
      'User Experience Design',
    ],
  },
  {
    title: 'Traffic Jam VR',
    description:
      'Traffic Jam VR is the product of a 3-day virtual reality game jam where professionals from various backgrounds came together to create virtual reality games.',
    date: 'August 2017',
    image: '/images/traffic-jam-vr.png',
    imageAlt: 'A low poly image of a street corner',
    link: './traffic-jam-vr',
    skills: [
      'Unity',
      'C#',
      'Virtual Reality',
      'Game Design',
      'Scene Design',
      'Level Design',
      'Rapid Prototyping',
      'Game Jam',
      'Team Collaboration',
    ],
  },
  {
    title: 'The Fourth Branch',
    description:
      'The Fourth Branch summarizes bills debated in Congress and allows users to vote on the summaries and compare their votes to those of their Congressmen.',
    date: 'January 2017',
    image: '/images/the-fourth-branch.png',
    imageAlt:
      'A logo with two parallel blue lines at the forefront and a red line in the background in the shape of a staple',
    link: './the-fourth-branch',
    skills: [
      'Product Management',
      'Project Management',
      'Business Analysis',
      'Basecamp',
      'Slack',
      'UX',
      'QA',
      'Mockups',
      'Marketing',
      'Content Creation',
      'Social Media Management',
      'Event Planning',
      'Community Engagement',
    ],
  },
  {
    title: 'Memorial Website',
    description:
      'There are many ways to remember a lost relative, and with modern technology, we can immortalize their experiences.',
    date: 'October 2014',
    image: '/images/memorial-website.jpg',
    imageAlt:
      "A painted mural of a person with a hat, and the word 'Ferle' written under it",
    link: './memorial-website',
    skills: [
      'Wix',
      'UX',
      'UI',
      'Web Design',
      'Responsive Design',
      'Digital Preservation',
      'User-Centered Design',
    ],
  },
  {
    title: 'Customizable Phone Case',
    description:
      'In the early 2010s, the iPhone had a small battery, and owners were seeking to protect their phones while customizing the look. The customizable phone case sought to provide a dynamic look and improve battery life for iPhones.',
    date: 'July 2014',
    image: '/images/custom-phone-case.png',
    imageAlt: 'A mechanical engineering mockup of an old iphone with a case',
    link: './customizable-phone-case',
    skills: [
      'Product Management',
      'Project Management',
      'Hardware Design',
      'Product Design',
      'Prototyping',
      'Consumer Electronics',
    ],
  },
]

export const getAllSkills = (): string[] => {
  const skillsSet = new Set<string>()
  projects.forEach((project) => {
    project.skills.forEach((skill) => skillsSet.add(skill))
  })
  return Array.from(skillsSet)
}

export const filterProjects = (
  projects: Project[],
  selectedSkills: string[]
): Project[] => {
  if (selectedSkills.length === 0) return projects
  return projects.filter((project) =>
    selectedSkills.every((skill) => project.skills.includes(skill))
  )
}
