import { Project } from './types'

export const projects: Project[] = [
  {
    title: 'Playermint Stream',
    description:
      'Explored a new approach to decentralized gaming where each player operates their own blockchain instead of relying on a global shared state.',
    date: 'December 2024',
    image: '/images/playerchain.png',
    imageAlt:
      'Chainsafe stream banner featuring David Amor, Martin Maurer, and Jay Albert',
    link: 'https://www.youtube.com/watch?v=1AgjLWaMQvw',
    skills: [
      'Blockchain Gaming',
      'Distributed Systems',
      'Game Development',
      'Architecture Design',
      'Research',
      'Streaming',
      'Developer Relations',
    ],
  },
  {
    title: 'Rock Paper Scissors Workshop',
    description:
      'Led an interactive workshop teaching students how to build a blockchain-powered Rock Paper Scissors game using Unity and Chainlink VRF.',
    date: 'December 2024',
    image: '/images/rps-workshop.jpeg',
    imageAlt: 'Rock Paper Scissors Workshop Tutorial Screenshot',
    link: 'https://www.youtube.com/watch?v=V9hxpnm-zEc',
    skills: [
      'Unity',
      'Blockchain Gaming',
      'Chainlink VRF',
      'Smart Contracts',
      'Game Development',
      'Technical Education',
      'Workshop Facilitation',
      'Developer Relations',
    ],
  },
  {
    title: 'ChainSafe Gaming SDK Update Stream',
    description:
      "Presented major updates to ChainSafe's Web3.Unity SDK and demonstrated token streaming functionality in a live stream",
    date: 'November 2024',
    image: '/images/sdk-updates.png',
    imageAlt: 'ChainSafe Gaming SDK Updates stream screenshot',
    link: 'https://www.youtube.com/live/rgArGYfoT8o',
    skills: [
      'Unity',
      'Web3',
      'Blockchain Gaming',
      'SDK Development',
      'Live Demo',
      'Technical Communication',
      'Developer Relations',
      'Streaming',
    ],
  },
  {
    title: 'Hatchyverse Stream',
    description:
      'An in-depth analysis of Hatchyverse, a decentralized gaming ecosystem that allows community members to build games using shared IP.',
    date: 'October 2024',
    image: '/images/hatchyverse.png',
    imageAlt: 'Hatchyverse platform analysis and overview',
    link: 'https://www.youtube.com/watch?v=QNr3moS0B3o',
    skills: [
      'Blockchain Gaming',
      'Game Development',
      'Web3',
      'Content Creation',
      'Analysis',
      'Research',
      'DAO',
      'NFTs',
      'Developer Relations',
      'Streaming',
    ],
  },
  {
    title: 'TruWorld Stream',
    description:
      'Explored TruWorld, an AR geo-location game that combines NFTs with real-world exploration. Similar to Pokemon Go but with blockchain integration, allowing players to claim and leave NFTs in physical locations.',
    date: 'October 2024',
    image: '/images/trumen-world.png',
    imageAlt: 'TruWorld stream showcase',
    link: 'https://www.youtube.com/watch?v=Y9EHHzF6Rzw',
    skills: [
      'AR Gaming',
      'Web3',
      'Blockchain Gaming',
      'NFTs',
      'Geo-location',
      'Game Development',
      'Content Creation',
      'Developer Relations',
      'Streaming',
    ],
  },
  {
    title: 'CLUAIDO Stream',
    description:
      'Explored CLUAIDO, an AI-powered detective game where players solve procedurally generated murder cases by freely interrogating AI-driven suspects.',
    date: 'September 2024',
    image: '/images/cluaido-stream.png',
    imageAlt: 'CLUAIDO game stream showcase',
    link: 'https://www.youtube.com/watch?v=SdJ9oo9d2Os',
    skills: [
      'AI Gaming',
      'ChatGPT Integration',
      'Game Development',
      'Procedural Generation',
      'Steam Development',
      'Content Creation',
      'Game Analysis',
      'Developer Relations',
      'Streaming',
    ],
  },
  {
    title: 'Quantum Command Stream',
    description:
      'Streamed with Quantum Command, a shooter game that adapts its maps based on player behavior and equipment. The game features innovative prize pool mechanics where players can compete for rewards generated from optional pay-to-play entries.',
    date: 'September 2024',
    image: '/images/quantum-command.png',
    imageAlt: 'Quantum Command game analysis stream',
    link: 'https://www.youtube.com/watch?v=RMemvjcBoNE',
    skills: [
      'Game Analysis',
      'Player Analytics',
      'Blockchain Gaming',
      'Game Development',
      'Content Creation',
      'Developer Relations',
      'Streaming',
    ],
  },
  {
    title: 'HackFS Winner Stream',
    description:
      'Featured the winning project from HackFS, showcasing a PvP battle game that combines Monaverse maps with ChainSafe SDK.',
    date: 'July 2024',
    image: '/images/hackfs-winner.png',
    imageAlt: 'HackFS Winner stream showing NFT battle game demo',
    link: 'https://www.youtube.com/watch?v=rTQhJHbDaWM',
    skills: [
      'Blockchain Gaming',
      'NFTs',
      'Monaverse',
      'ChainSafe SDK',
      'Game Development',
      'Hackathon Projects',
      'Content Creation',
      'Developer Relations',
      'Streaming',
    ],
  },
  {
    title: 'Hyperplay & Coinracer Stream',
    description:
      'Explored Hyperplay, a trusted game launcher for blockchain games, featuring Coinracer. Demonstrated how ChainSafe Gaming SDK supports Hyperplay login and discussed how the platform vets and curates trusted Web3 games for players.',
    date: 'July 2024',
    image: '/images/hyperplay-stream.jpeg',
    imageAlt: 'Hyperplay and Coinracer platform showcase stream',
    link: 'https://www.youtube.com/watch?v=70DahC2GHXs',
    skills: [
      'Game Distribution',
      'Platform Development',
      'SDK Integration',
      'Blockchain Gaming',
      'Game Curation',
      'Content Creation',
      'Developer Relations',
      'Streaming',
    ],
  },
  {
    title: 'On-Chain Lootboxes at GDC',
    description:
      'Developed and presented a technical demonstration of on-chain lootboxes at the Game Developers Conference (GDC).',
    date: 'April 2024',
    image: '/images/loot-gdc.png',
    imageAlt: 'ChainSafe GDC Lootboxes presentation',
    link: 'https://blog.chainsafe.io/onchain-lootboxes-gdc/',
    skills: [
      'Blockchain Gaming',
      'Smart Contracts',
      'Solidity',
      'Web3',
      'Technical Writing',
      'Documentation',
      'Public Speaking',
      'Game Development',
    ],
  },
  {
    title: 'Lilypad Frontend Guide',
    description:
      'Created a comprehensive guide for developers to set up and customize their Lilypad Network frontend, improving the developer experience for the platform.',
    date: 'December 2023',
    image: '/images/lilypad-frontend.avif',
    imageAlt:
      'Screenshot of a code editor showing React components for Lilypad Network',
    link: './lilypad-frontend',
    skills: [
      'Technical Writing',
      'Documentation',
      'React',
      'Next.js',
      'TypeScript',
      'Frontend Development',
      'UI Development',
      'Git',
      'Developer Relations',
    ],
  },
  {
    title: 'Lilypad Network',
    description:
      'Contributed to the development of a decentralized compute network, focusing on improving user experience and documentation.',
    date: 'December 2023',
    image: '/images/lilypad.avif',
    imageAlt: 'Lilypad Network logo showing a modern, stylized lily pad',
    link: './lilypad',
    skills: [
      'Documentation',
      'Distributed Computing',
      'Blockchain',
      'Docker',
      'Linux',
      'Content Creation',
      'Project Management',
      'Developer Relations',
    ],
  },
  {
    title: 'The Machine Dreams',
    description:
      'An art project that uses AI to generate art every hour based on what is trending on Google in the U.S.',
    date: 'October 2023',
    image: '/images/machine_dream.jpg',
    imageAlt:
      'A circular logo with an M in the middle and colorful clouds at the bottom.',
    link: 'https://www.themachinedreams.com/about',
    skills: [
      'Python',
      'Typescript',
      'Twitter API',
      'Stability AI SDK',
      'Thirdweb SDK',
      'IPFS',
      'NFT.storage',
      'Solidity',
      'Openzeppelin',
      'Sepolia',
      'Ethereum',
      'Opensea',
      'Chainlink',
      'Google Cloud Platform',
    ],
  },
  {
    title: 'Web2 to Web3 Game Development Workshop',
    description:
      'Led a hands-on workshop at ETHDenver demonstrating how to transform a traditional game into a blockchain-enabled experience.',
    date: 'February 2023',
    image: '/images/ethdenver-workshop.avif',
    imageAlt: 'ETHDenver Workshop presentation screenshot',
    link: './web3-game-workshop',
    skills: [
      'Game Development',
      'Web3',
      'Smart Contracts',
      'Public Speaking',
      'Technical Education',
      'Live Coding',
      'Workshop Facilitation',
      'Blockchain',
      'Developer Relations',
    ],
  },
  {
    title: 'Mix3d Clothing',
    description: 'A clothing brand concept from the Mix3d community.',
    date: 'December 2022',
    image: '/images/shirt.png',
    imageAlt:
      'A 3D model of a black shirt with the Mix3d community logo on the front.',
    link: './mix3d-clothing',
    skills: [
      'Moralis',
      'Meta Mask',
      'Goerli Test Network',
      'Javascript',
      'HTML',
      'CSS',
      'Figma',
      'Clo3d',
      'Spark AR',
      'Augmented Reality',
      'Vectary',
      'Magica Voxel',
      'Github',
    ],
  },
  {
    title: 'Exploring Web3 Finance',
    description:
      'Snapshots of my experiences in cryptocurrency investing using DeFi tools and working with TradFi organizations.',
    date: 'October 2022',
    image: '/images/tokensets.png',
    imageAlt:
      'Two blue circle overlaping eachother with the top circle containing a fade on the right side and the bottom circle containing a fade on the left side. The fades make the circles appear vaguely in the shape of an S',
    link: './tokensets',
    skills: [
      'Tokensets',
      'Meta Mask',
      'Polygon',
      'DeFi',
      'TradFi',
      'Indexes',
      'Investment Analysis',
      'Writing',
    ],
  },
  {
    title: 'Invisible Maze Game',
    description:
      'An invisible maze game to onboard users to Metamask and Decentraland.',
    date: 'January 2022',
    image: '/images/invisible-maze.png',
    imageAlt: 'A view of an invisible maze game made in Decentraland',
    link: './invisible-maze-game',
    skills: [
      'Decentraland',
      'Meta Mask',
      'Ethereum Network',
      'Etherscan',
      'Notion',
      'Game Design',
    ],
  },
  {
    title: 'Mix3d',
    description:
      'Mix3d is a community connecting, organizing, and building on Web 3.',
    date: 'January 2022',
    image: '/images/mix3d.png',
    imageAlt: 'A logo of circles in a spiral with varrying colors',
    link: './mix3d',
    skills: [
      'Notion',
      'Discord',
      'Meta Mask',
      'Partybid',
      'Mirror',
      'Community Management',
      'Consulting',
      'Project Management',
      'Educational Content',
    ],
  },
  {
    title: 'Crypto Banking Guide',
    description:
      'Authored a comprehensive guide on maximizing interest earnings through crypto banking platforms and stablecoins.',
    date: 'May 2021',
    image: '/images/crypto-banking.webp',
    imageAlt:
      'Graph showing crypto interest rates compared to traditional banking',
    link: 'https://jonathan-albert.medium.com/earn-more-interest-with-crypto-banking-4657bb167a32',
    skills: [
      'DeFi',
      'Crypto Banking',
      'Technical Writing',
      'Yield Farming',
      'Research',
      'Financial Education',
      'Content Creation',
    ],
  },
  {
    title: 'Werewolf',
    description: 'A social deduction game utilizing webcams on a browser.',
    date: 'September 2020',
    image: '/images/werewolf.png',
    imageAlt:
      'A sign in screen with the word Werewolf at the top in a font that looks like bloody letters',
    link: './werewolf',
    skills: [
      'Javascript',
      'React',
      'JSX',
      'HTML',
      'CSS',
      'Dafont',
      'Material UI',
      'AniJS',
      'Express',
      'Morgan',
      'Sequelize',
      'Firebase',
      'Twilio',
      'Github',
      'Game Design',
    ],
  },
  {
    title: 'Grace Potter',
    description: 'An e-commerce website selling handmade pottery.',
    date: 'August 2020',
    image: '/images/grace-potter.png',
    imageAlt: 'An icon of a pottery vase',
    link: './grace-potter',
    skills: [
      'Javascript',
      'React',
      'JSX',
      'HTML',
      'CSS',
      'Redux',
      'Reactstrap',
      'WebSocket',
      'Express',
      'Sequelize',
      'Axios',
      'PostgreSQL',
      'Postman',
      'Nodemailer',
      'Stripe',
      'Github',
    ],
  },
  {
    title: 'Mobile Vendor',
    description: 'A platform to connect mobile vendors to potential customers.',
    date: 'August 2020',
    image: '/images/mobile-vendor.png',
    imageAlt:
      'A smart phone overlayed on top of a map with icons for mobile vendors',
    link: './mobile-vendor',
    skills: [
      'Javascript',
      'React Native',
      'MapView',
      'Expo',
      'Redux',
      'HTML',
      'CSS',
      'Firebase',
      'Github',
    ],
  },
  {
    title: 'Thought Card',
    description:
      'Augmented Reality (AR) allows developers to pack information into images. Business cards can now contain links, videos, 3D objects, scenes, games, and more.',
    date: 'April 2020',
    image: '/images/thought-card.png',
    imageAlt:
      "A blue business card with a quote that reads 'The convential mind is passive - it consumes information and regurgitates it in familiar forms. The dimensional mind is active. Transforming everything it digests into something new and original, creating instead of consuming' by Robert Greene from the book Mastery on page 177.",
    link: './thought-card',
    skills: ['Unity', 'Vuforia', 'C#', 'Augmented Reality'],
  },
  {
    title: 'Wix',
    description:
      'A stint as a freelancer for Wix websites fueled by word-of-mouth recommendations.',
    date: 'March 2020',
    image: '/images/wix.png',
    imageAlt: 'The wix website logo',
    link: './wix',
    skills: [
      'Wix',
      'UI',
      'Client Relations',
      'Business Analysis',
      'Project Management',
      'Budgeting',
    ],
  },
  {
    title: 'Blotto',
    description:
      'A drinking card game that served as a proof of concept for launching applications using Unity on the Google Play store.',
    date: 'January 2020',
    image: '/images/blotto.png',
    imageAlt:
      "A flat image of a body with its head in a toilet and the words 'Blotto' written under the image.",
    link: './blotto',
    skills: [
      'Unity',
      'C#',
      'UI',
      'Game Design',
      'Animation',
      'Sound',
      'Project Management',
    ],
  },
  {
    title: 'LiveIn',
    description:
      'LiveIn was a real estate brokerage that utilized augmented reality to engage with potential clients.',
    date: 'October 2019',
    image: '/images/livein.png',
    imageAlt:
      'A logo of a leaf that has lines across it similar to that of a circuit board',
    link: './livein',
    skills: [
      'Project Management',
      'Business Analysis',
      'UX',
      'Trello',
      'Real Estate',
      'Augmented Reality',
    ],
  },
  {
    title: 'Augmented Piano Lessons',
    description:
      'The future of learning how to play music will involve projections that augment the instrument to gamify the learning process.',
    date: 'December 2017',
    image: '/images/ar-piano-lessons.png',
    imageAlt: 'Piano keys on with a background of musical notes',
    link: './ar-piano-lessons',
    skills: ['Unity', 'C#', 'Augmented Reality', 'Animation', 'Sound'],
  },
  {
    title: 'Traffic Jam VR',
    description:
      'Traffic Jam VR is the product of a 3-day virtual reality game jam where professionals from various backgrounds came together to create virtual reality games.',
    date: 'August 2017',
    image: '/images/traffic-jam-vr.png',
    imageAlt: 'A low poly image of a street corner',
    link: './traffic-jam-vr',
    skills: [
      'Unity',
      'C#',
      'Virtual Reality',
      'Game Design',
      'Sound',
      'Scene Design',
      'Level Design',
    ],
  },
  {
    title: 'The Fourth Branch',
    description:
      'The Fourth Branch summarizes bills debated in Congress and allows users to vote on the summaries and compare their votes to those of their Congressmen.',
    date: 'January 2017',
    image: '/images/the-fourth-branch.png',
    imageAlt:
      'A logo with two parallel blue lines at the forefront and a red line in the background in the shape of a staple',
    link: './the-fourth-branch',
    skills: [
      'Product Management',
      'Project Management',
      'Business Analysis',
      'Basecamp',
      'Slack',
      'UX',
      'QA',
      'Mockups',
      'Marketing',
      'Content Creation',
      'Twitter',
      'Instagram',
      'Facebook',
      'LinkedIn',
      'Event Planning',
    ],
  },
  {
    title: 'Memorial Website',
    description:
      'There are many ways to remember a lost relative, and with modern technology, we can immortalize their experiences.',
    date: 'October 2014',
    image: '/images/memorial-website.jpg',
    imageAlt:
      "A painted mural of a person with a hat, and the word 'Ferle' written under it",
    link: './memorial-website',
    skills: ['Wix', 'UX', 'UI'],
  },
  {
    title: 'Customizable Phone Case',
    description:
      'In the early 2010s, the iPhone had a small battery, and owners were seeking to protect their phones while customizing the look. The customizable phone case sought to provide a dynamic look and improve battery life for iPhones.',
    date: 'July 2014',
    image: '/images/custom-phone-case.png',
    imageAlt: 'A mechanical engineering mockup of an old iphone with a case',
    link: './customizable-phone-case',
    skills: ['Product Management', 'Project Management', 'Hardware Design'],
  },
]

export const getAllSkills = (): string[] => {
  const skillsSet = new Set<string>()
  projects.forEach((project) => {
    project.skills.forEach((skill) => skillsSet.add(skill))
  })
  return Array.from(skillsSet)
}

export const filterProjects = (
  projects: Project[],
  selectedSkills: string[]
): Project[] => {
  if (selectedSkills.length === 0) return projects
  return projects.filter((project) =>
    selectedSkills.every((skill) => project.skills.includes(skill))
  )
}
